### ISSUE TITLE
Error: context must be a dict rather than SekizaiContext.

### ISSUE THREAD

**Issue by stasfilin** [divio/django-sekizai#74]
Good evening,
I got error:
```html
TypeError at /en/login/
context must be a dict rather than SekizaiContext.
```

```python
from sekizai.context import SekizaiContext

context = SekizaiContext(request, {'error': error, 'form': form})
return render_to_response('login.html', context)
```

**Comment by ojii** [comment]
Please include your template (and sub-templates) as well as a full traceback. The problem is you're isolating the context somewhere (eg in a template tag). See for example #73

**Comment by jribbens** [comment]
It's more likely that @stasfilin is using Django 1.11, which disallows calling `render_to_response()` with a `context` parameter which is not a `dict`. You cannot use `SekizaiContext` with Django 1.11. See https://code.djangoproject.com/ticket/27258 for details.
