### ISSUE TITLE
Allow running sdist setup.py test

### ISSUE THREAD

**Issue by jayvdb** [divio/django-sekizai#81]
For the next release, it would be helpful if the sdist uploaded to PyPi supported running `setup.py test`, e.g. by including and running `runtests.py`

**Comment by FinalAngel** [comment]
this has been implemented :)

**Comment by jayvdb** [comment]
Looks like it was part of https://github.com/divio/django-sekizai/pull/83 , so isnt in v1.0.0 .  Looking forward to the next release.
