### ISSUE TITLE
Can`t use render_to_string without a given request

### ISSUE THREAD

**Issue by Myzel394** [divio/django-sekizai#88]
If I don\`t pass a `request` object, I always get this error:

```
You must enable the 'sekizai.context_processors.sekizai' template context processor or use 'sekizai.context.SekizaiContext' to render your templates.
```

If you know how to solve this error, please let me know.

**Comment by FinalAngel** [comment]
@Myzel394 make sure to configure it correctly, depending on the Django version used: https://django-sekizai.readthedocs.io/en/latest/#configuration
